import "./globals.css";
import { Montserrat } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Footer, Header } from "../components";
import { neobrutalism } from "@clerk/themes";
const montserrat = Montserrat({ subsets: ["latin", "cyrillic"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <ClerkProvider appearance={{baseTheme: neobrutalism}} publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
          <html lang="en">
          <body className={montserrat.className}>
          <Header />
          {children}
          <Footer />
          </body>
          </html>
        </ClerkProvider>
  );
}
