import "./globals.css";
import { Montserrat } from "next/font/google";
import {Footer, Header} from "@/components";

const montserrat = Montserrat({ subsets: ["latin", "cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
        </body>

    </html>
  );
}
